### ISSUE TITLE
X64 : clibpe.cpp conversion from 'DWORD_PTR' to 'DWORD'

### ISSUE THREAD

**Issue by mambolevis** [jovibor/libpe#1]
Hi,
The following errors are shown when I compile the library:

clibpe.cpp
```
... clibpe.cpp(843): error C2397: conversion from 'DWORD_PTR' to 'DWORD' requires a narrowing conversion
.. clibpe.cpp(1053): error C2397: conversion from 'size_t' to 'DWORD' requires a narrowing conversion
```
Thank you 
I found this link: https://social.msdn.microsoft.com/Forums/de-DE/bee57188-9d11-4d4b-a345-67d19b49b29f/dword-cast-dwordptr-x64?forum=visualcplusde

**Comment by jovibor** [comment]
Actually these errors comes from the fact that you are compiling under the x64 target platform, while this library is mostly used and developed in x86 in mind :) 
Anyway, i fixed these errors, you can pull now.
Let me know if it's working for you.

**Comment by mambolevis** [comment]
Yes, it works perfectly. I checked both platforms` x86 and x64` and for each of them also `debug and release`. Thanks.

The next step is to test Pepper for both x86 and x64 (`both debug and release`).  I have some results:
1) x86 (debug) : It doesn't work
2) x86 (release): It compiles but when I select a *.dll like in your example the information is not shown and the application disappears.

![image](https://user-images.githubusercontent.com/13024208/53595415-7af08c80-3b9d-11e9-93db-1d7ef76a7e5d.png)

3) x64 (debug) : It didn't work
4) x64 (release) : It didn't work

Thank you.

**Comment by jovibor** [comment]
Concerning Pepper: it was not even tested for build against x64, it's still in development.
Now, could you please test it by open standard Windows notepad.exe, what happens?
If it doesn't work, then could you download latest Pepper release https://github.com/jovibor/Pepper/releases/latest and try it then.
I need to understand where issue comes from: App itself, or your compilation.

**Comment by mambolevis** [comment]
Ok, lets focus first on the **`x86`**.  Here some result tests:
- I build the release version of both libpe.lib and `Pepper_0.8.4 `(latest release). 
- I am using the **`x86`** libpe.dll version
- Test with notepad.exe: When I the notepad.exe like in your example the information is not shown and the application disappeared.
- Attached you can find a zip file with the binaries
[Pepper-0.8.4_test_x86_bin.zip](https://github.com/jovibor/libpe/files/2918516/Pepper-0.8.4_test_x86_bin.zip)

- This is the build process output:
```
1>------ Build started: Project: Pepper, Configuration: Release Win32 ------
1>stdafx.cpp
1>ChildFrm.cpp
1>FileLoader.cpp
1>HexCtrl.cpp
1>ScrollEx.cpp
1>ListEx.cpp
1>SplitterEx.cpp
1>ViewLeft.cpp
1>MainFrm.cpp
1>Pepper.cpp
1>PepperDoc.cpp
1>ViewRightBL.cpp
1>ViewRightTR.cpp
1>ViewRightBR.cpp
1>ViewRightTL.cpp
1>TreeEx.cpp
1>Generating code
1> ...\pepper-0.8.4_test_x86\pepper\viewrightbl.cpp(234): warning C4715: 'CViewRightBL::CreateHexRichHeaderEntry': not all control paths return a value
1>All 3550 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
1>Finished generating code
1>Pepper.vcxproj -> ...\Pepper-0.8.4_test_x86\Release\Pepper.exe
1>....\Pepper-0.8.4_test_x86\Pepper\\verinfo\set_verinfo.ps1 : Die Datei
1>"....\Pepper-0.8.4_test_x86\Pepper\verinfo\set_verinfo.ps1" kann nicht geladen werden, da die Ausführung von Skripts auf diesem System deaktiviert ist. Weitere Informationen finden Sie unter
1>"about_Execution_Policies" (https:/go.microsoft.com/fwlink/?LinkID=135170).
1>In Zeile:1 Zeichen:1
1>+ ....\Pepper-0.8.4_test_x86\....
1>+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1>    + CategoryInfo          : Sicherheitsfehler: (:) [], PSSecurityException
1>    + FullyQualifiedErrorId : UnauthorizedAccess
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "powershell.exe ....\Pepper-0.8.4_test_x86\Pepper\\verinfo\set_verinfo.ps1 ....\Pepper-0.8.4_test_x86\Release\Pepper.exe
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "Pepper.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
Thanks

**Comment by jovibor** [comment]
Your attached files failed to run properly on my side. But when i replaced Pepper.exe from archive with my owm Pepper.exe it worked well.
So, the problem is somewhere in Pepper compilation.

I attached two sets of newly build apps (x86 and x64).
Could you please test it and see, if any of it (or both) works as expected (could open .exe or .dll and see the inner layouts).
[PepperTest.zip](https://github.com/jovibor/libpe/files/2918758/PepperTest.zip)
Thank you.

Also, all the changes are reflected in repository.

**Comment by mambolevis** [comment]
Hi, I cloned the master repo and build both platforms in release mode and now it is working properly (`in all platforms`)

![image](https://user-images.githubusercontent.com/13024208/53631216-5387d700-3c12-11e9-9189-9488c8e4f8fc.png)

I think it is good idea to set up the project for both platforms (`x86 and x64`) including `debug` and `release `versions.

I found an article in wikipedia to describe the PE format: https://en.wikipedia.org/wiki/Portable_Executable
Maybe you can refer this or add your own description.  It is also interesting to refer other tools such `dependency walker` http://www.dependencywalker.com/

Thank you, nice project!

**Comment by jovibor** [comment]
> I think it is good idea to set up the project for both platforms (x86 and x64)  

I definitely will.

Thanks for participation.

**Comment by mambolevis** [comment]
Please consider the option of keeping the same name of the library (`libpe.lib`) in both platforms but using different directories, see example below:

![image](https://user-images.githubusercontent.com/13024208/53695260-68529f00-3db9-11e9-8d7a-dcb86534064f.png)

Thank you!

**Comment by jovibor** [comment]
What's the exact issue you are facing?
Right now Pepper will link against the `.dll` it needed - x86 or x64, debug or release.
You just need to put corresponding `.lib` in `lib` sub-folder. 
Depending on build target compiler will choose appropriate `.lib` automatically.

**Comment by mambolevis** [comment]
There is no issue, it is just a recommendation. 
Usually the library have the same name in both platforms. It facilitates the build process especially when you are using other build system different than Visual Studio :-)
 
- In your case. for instance, you are linking Pepper against (`libpe.lib` or `libpe_x64`) depending on the platform:
- In my case I only link against `libpe.lib` but I select automatically the library from different directories, for example:
  for x86, I have a folder: `lib/x86/libpe.lib` and for x64, I have a folder: `lib/x64/libpe.lib`

**Comment by jovibor** [comment]
Actually it's always very convenient to differentiate the type of the binary just by glance.
I your case, if you have defined two separate folders for x86 and x64, then what's preventing you from defining two separate `.lib` name for the same thing: `x86=libpe.lib`  `x64=libpe_x64.lib`?

**Comment by mambolevis** [comment]
> Actually it's always very convenient to differentiate the type of the binary just by glance.

Yes, it is but it usually introduces changes in the name of the library. In your case, you will need the following distinctions: 
- `Libpe_debug.lib` and `Libdp.lib`
- `Libpe_debug_x64.lib` and `Libpe_x64.lib`

In my case, the library has only one name `Libpe.lib`. 

Please, take a look at the result .exe file after the build process; its name is the same but it is located in different folders for each platform and version (debug and release). As I told you it is a convention or maybe a recommendation.

**Comment by jovibor** [comment]
>  As I told you it is a convention or maybe a recommendation.

I don't see it as a convention.
And btw, you can place these `.lib` in whatever folder you want yourself.

P.S. For instance, just related post: https://stackoverflow.com/questions/739023/library-name-for-x32-vs-x64

**Comment by mambolevis** [comment]
Ok. In my case it is indifferent. 
Thanks
